version: 2.1

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: "./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   install"

jobs:

  jdk17:
    docker:
      - image: cimg/openjdk:17.0.6
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    parallelism: 3
    steps: *build_steps

workflows:
  build_and_test:
    jobs:
      - jdk17